// <auto-generated />
using System;
using IncrelutionAutomationEditor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncrelutionAutomationEditor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118122150_RemoveActionsFromDatabase")]
    partial class RemoveActionsFromDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.Loadout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Loadouts");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.LoadoutActionSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomationLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoadoutId");

                    b.ToTable("LoadoutActionSettings");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.LoadoutActionSetting", b =>
                {
                    b.HasOne("IncrelutionAutomationEditor.Api.Models.Loadout", "Loadout")
                        .WithMany("ActionSettings")
                        .HasForeignKey("LoadoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loadout");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.Loadout", b =>
                {
                    b.Navigation("ActionSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
