// <auto-generated />
using System;
using IncrelutionAutomationEditor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncrelutionAutomationEditor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123184341_AddLoadoutSharing")]
    partial class AddLoadoutSharing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.Loadout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("Loadouts");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.LoadoutShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoadoutId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAttribution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ViewLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoadoutId");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.ToTable("LoadoutShares");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.SavedShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadoutShareId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoadoutShareId");

                    b.HasIndex("UserId", "LoadoutShareId")
                        .IsUnique();

                    b.ToTable("SavedShares");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.Folder", b =>
                {
                    b.HasOne("IncrelutionAutomationEditor.Api.Models.Folder", "Parent")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.Loadout", b =>
                {
                    b.HasOne("IncrelutionAutomationEditor.Api.Models.Folder", "Folder")
                        .WithMany("Loadouts")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.LoadoutShare", b =>
                {
                    b.HasOne("IncrelutionAutomationEditor.Api.Models.Loadout", "Loadout")
                        .WithMany()
                        .HasForeignKey("LoadoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loadout");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.SavedShare", b =>
                {
                    b.HasOne("IncrelutionAutomationEditor.Api.Models.LoadoutShare", "LoadoutShare")
                        .WithMany()
                        .HasForeignKey("LoadoutShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadoutShare");
                });

            modelBuilder.Entity("IncrelutionAutomationEditor.Api.Models.Folder", b =>
                {
                    b.Navigation("Loadouts");

                    b.Navigation("SubFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
